repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.4
  hooks:
  - id: clang-format
    types_or: [c++, c, objective-c, objective-c++]
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args: ["--line-length", "100"]
    types: [python]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black"]
    types: [python]
